import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MapPin } from 'lucide-react';
const DealHeader = ({ deal }) => {
    // Calculate LVRs
    const startLVR = (deal.propertyDetails.firstMortgage / deal.propertyValue) * 100;
    const combinedLVR = ((deal.propertyDetails.firstMortgage + deal.loanAmount) / deal.propertyValue) * 100;
    return (_jsxs("div", { className: "bg-white rounded-lg shadow-sm overflow-hidden", children: [_jsxs("div", { className: "relative h-96", children: [_jsx("img", { src: deal.images.exterior, alt: `${deal.suburb} property`, className: "w-full h-full object-cover" }), _jsxs("div", { className: "absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-8", children: [_jsx("h1", { className: "text-3xl font-semibold text-white mb-2", children: deal.suburb }), _jsxs("div", { className: "flex items-center text-white/90", children: [_jsx(MapPin, { className: "h-5 w-5 mr-2" }), _jsx("span", { children: "Sydney, NSW" })] })] }), _jsxs("div", { className: "absolute top-6 right-6 flex flex-col items-end space-y-2", children: [_jsx("div", { className: `px-4 py-2 rounded-lg ${(deal.irr ?? 0) >= 20 ? 'bg-green-100 text-green-800' :
                                    (deal.irr ?? 0) >= 15 ? 'bg-green-50 text-green-700' :
                                        'bg-green-50 text-green-600'}`, children: _jsxs("span", { className: "font-semibold", children: [deal.irr?.toFixed(2) ?? 'N/A', "% IRR"] }) }), _jsx("div", { className: "px-4 py-2 rounded-lg bg-white/90 text-gray-900", children: _jsxs("span", { className: "font-semibold", children: ["Loan: $", deal.loanAmount?.toLocaleString()] }) })] })] }), _jsx("div", { className: "p-8", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600", children: "Proptrack AVM" }), _jsxs("div", { className: "text-xl font-semibold", children: ["$", deal.propertyValue?.toLocaleString() ?? 'N/A'] })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600", children: "Equihome AVM (Discounted)" }), _jsxs("div", { className: "text-xl font-semibold", children: ["$", (deal.propertyValue * 0.9).toLocaleString()] })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600", children: "Discount Rate" }), _jsx("div", { className: "text-xl font-semibold", children: "10%" })] })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600", children: "Existing Debt" }), _jsxs("div", { className: "text-xl font-semibold", children: ["$", deal.propertyDetails.firstMortgage?.toLocaleString() ?? '0'] })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600", children: "LVR Start" }), _jsxs("div", { className: "text-xl font-semibold", children: [startLVR.toFixed(2), "%"] })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600", children: "Combined LVR" }), _jsxs("div", { className: "text-xl font-semibold", children: [combinedLVR.toFixed(2), "%"] })] })] })] }) })] }));
};
export default DealHeader;
