import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Building2, TrendingUp, DollarSign, Clock } from 'lucide-react';
const DealCard = ({ deal, index }) => {
    // Calculate combined LTV including existing mortgage, with null check
    const firstMortgage = deal.propertyDetails?.firstMortgage || 0;
    const combinedLTV = ((firstMortgage + deal.loanAmount) / deal.propertyValue) * 100;
    return (_jsx(Link, { to: `/deal/${deal.id}`, className: "block", children: _jsxs("div", { className: "bg-white rounded-lg shadow-sm hover:shadow-md transition-shadow overflow-hidden", children: [_jsxs("div", { className: "relative h-48", children: [_jsx("img", { src: deal.images?.exterior || 'https://images.unsplash.com/photo-1568605114967-8130f3a36994', alt: `${deal.suburb} property`, className: "w-full h-full object-cover" }), _jsx("div", { className: "absolute top-4 right-4 bg-white px-3 py-1 rounded-full shadow-sm", children: _jsxs("span", { className: `font-medium ${deal.irr >= 20 ? 'text-green-600' :
                                    deal.irr >= 15 ? 'text-green-500' : 'text-green-400'}`, children: [deal.irr?.toFixed(2), "% IRR"] }) })] }), _jsxs("div", { className: "p-6", children: [_jsx("div", { className: "flex items-center justify-between mb-4", children: _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900", children: deal.suburb }), _jsxs("div", { className: "flex items-center text-gray-600 mt-1", children: [_jsx(Building2, { className: "h-4 w-4 mr-1" }), _jsx("span", { children: deal.propertyType })] })] }) }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-gray-600", children: "Property Value" }), _jsxs("span", { className: "font-medium", children: ["$", deal.propertyValue?.toLocaleString()] })] }), _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-gray-600", children: "Loan Amount" }), _jsxs("span", { className: "font-medium", children: ["$", deal.loanAmount?.toLocaleString()] })] }), _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-gray-600", children: "LTV" }), _jsxs("span", { className: "font-medium", children: [combinedLTV.toFixed(2), "%"] })] }), _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-gray-600", children: "Term" }), _jsxs("div", { className: "flex items-center text-gray-900 font-medium", children: [_jsx(Clock, { className: "h-4 w-4 mr-1" }), _jsxs("span", { children: [deal.loanTerms.term, " years"] })] })] }), _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-gray-600", children: "Property Growth Rate" }), _jsxs("div", { className: "flex items-center text-green-600 font-medium", children: [_jsx(TrendingUp, { className: "h-4 w-4 mr-1" }), _jsxs("span", { children: [deal.propertyDetails?.yearlyGrowth || 0, "%"] })] })] }), _jsx("div", { className: "pt-3 border-t", children: _jsx("div", { className: "flex items-center justify-between text-sm", children: _jsxs("div", { className: "flex items-center text-indigo-600", children: [_jsx(DollarSign, { className: "h-4 w-4 mr-1" }), _jsxs("span", { children: ["Total Return: $", ((deal.interestEarned || 0) + (deal.equihomeFeeEarned || 0)).toLocaleString()] })] }) }) })] })] })] }) }, `deal-${deal.id}-${index}`));
};
export default DealCard;
