import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CheckCircle, XCircle, Building2, Scale } from 'lucide-react';
import ReturnProjections from './ReturnProjections';
const ResultsView = ({ data, decision }) => {
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "bg-white rounded-lg shadow-sm p-8", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h2", { className: "text-2xl font-semibold", children: "Investment Analysis" }), decision.approved ? (_jsxs("div", { className: "flex items-center text-green-600", children: [_jsx(CheckCircle, { className: "h-6 w-6 mr-2" }), _jsx("span", { className: "font-semibold", children: "Approved" })] })) : (_jsxs("div", { className: "flex items-center text-red-600", children: [_jsx(XCircle, { className: "h-6 w-6 mr-2" }), _jsx("span", { className: "font-semibold", children: "Not Approved" })] }))] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600 mb-1", children: "Property Value" }), _jsxs("div", { className: "text-2xl font-semibold", children: ["$", data.currentValue.toLocaleString()] })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600 mb-1", children: "Loan Amount" }), _jsxs("div", { className: "text-2xl font-semibold", children: ["$", decision.loanAmount.toLocaleString()] })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600 mb-1", children: "LTV Ratio" }), _jsxs("div", { className: "text-2xl font-semibold", children: [decision.ltv.toFixed(1), "%"] })] })] }), _jsx("div", { className: "mt-6 p-4 bg-gray-50 rounded-lg", children: _jsx("p", { className: "text-gray-700", children: decision.explanation }) })] }), _jsx(ReturnProjections, { decision: decision, propertyValue: data.currentValue, loanAmount: decision.loanAmount }), _jsxs("div", { className: "bg-white rounded-lg shadow-sm p-8", children: [_jsxs("div", { className: "flex items-center mb-6", children: [_jsx(Scale, { className: "h-6 w-6 text-indigo-600 mr-2" }), _jsx("h3", { className: "text-xl font-semibold", children: "Risk Assessment" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600", children: "Risk Level" }), _jsx("div", { className: `text-lg font-semibold ${decision.riskLevel === 'low'
                                                    ? 'text-green-600'
                                                    : decision.riskLevel === 'medium'
                                                        ? 'text-yellow-600'
                                                        : 'text-red-600'}`, children: decision.riskLevel.charAt(0).toUpperCase() + decision.riskLevel.slice(1) })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-600", children: "Property Type" }), _jsx("div", { className: "text-lg font-semibold", children: data.propertyType })] })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("h4", { className: "text-sm font-medium text-gray-700 mb-3", children: "Risk Factors" }), _jsxs("ul", { className: "space-y-2 text-sm text-gray-600", children: [_jsxs("li", { children: ["\u2022 LTV Ratio: ", decision.ltv.toFixed(1), "% ", decision.ltv > 70 ? '(High)' : decision.ltv > 65 ? '(Medium)' : '(Low)'] }), _jsx("li", { children: "\u2022 Fixed Interest Rate: 5.0%" }), _jsx("li", { children: "\u2022 No Monthly Payments Required" }), _jsx("li", { children: "\u2022 Early Exit Option Available" }), _jsxs("li", { children: ["\u2022 Property Type: ", data.propertyType] })] })] })] })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-sm p-8", children: [_jsxs("div", { className: "flex items-center mb-6", children: [_jsx(Building2, { className: "h-6 w-6 text-indigo-600 mr-2" }), _jsx("h3", { className: "text-xl font-semibold", children: "Property Details" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm text-gray-600 mb-2", children: "Address" }), _jsx("div", { className: "text-lg", children: data.propertyAddress })] }), _jsxs("div", { children: [_jsx("div", { className: "text-sm text-gray-600 mb-2", children: "Current Mortgage" }), _jsxs("div", { className: "text-lg", children: ["$", data.mortgageBalance.toLocaleString()] })] })] })] })] }));
};
export default ResultsView;
