import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Routes, Route, Navigate } from 'react-router-dom';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import InvestmentGrid from './components/InvestmentGrid';
import DealAnalysis from './components/DealAnalysis';
import FundDashboard from './components/FundDashboard';
import CIODashboard from './components/cio/CIODashboard';
import UnderwriteDemo from './components/UnderwriteDemo';
import WelcomeScreen from './components/WelcomeScreen';
import ConfidentialityScreen from './components/ConfidentialityScreen';
import HelpButton from './components/HelpButton';
import AssetReportButton from './components/AssetReportButton';
import AssetReport from './components/AssetReport';
import Pipeline from './components/Pipeline';
import TabInfo from './components/TabInfo';
import FinancialModeling from './components/FinancialModeling';
import PropTrackDemo from './components/PropTrackDemo';
const App = () => {
    return (_jsxs(_Fragment, { children: [_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(ConfidentialityScreen, {}) }), _jsx(Route, { path: "/welcome", element: _jsx(WelcomeScreen, {}) }), _jsx(Route, { path: "/asset-report", element: _jsx(AssetReport, {}) }), _jsx(Route, { path: "/proptrack", element: _jsx(PropTrackDemo, {}) }), _jsx(Route, { path: "/*", element: _jsxs("div", { className: "min-h-screen bg-gradient-to-br from-blue-50 to-blue-100", children: [_jsx(Navbar, {}), _jsx(TabInfo, {}), _jsx("main", { className: "py-12", children: _jsxs(Routes, { children: [_jsx(Route, { path: "/deals", element: _jsx(InvestmentGrid, {}) }), _jsx(Route, { path: "/deal/:id", element: _jsx(DealAnalysis, {}) }), _jsx(Route, { path: "/fund-dashboard", element: _jsx(FundDashboard, {}) }), _jsx(Route, { path: "/cio-dashboard", element: _jsx(CIODashboard, {}) }), _jsx(Route, { path: "/underwrite", element: _jsx(UnderwriteDemo, {}) }), _jsx(Route, { path: "/pipeline", element: _jsx(Pipeline, {}) }), _jsx(Route, { path: "/financial-modeling", element: _jsx(FinancialModeling, {}) }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/deals", replace: true }) })] }) }), _jsx(Footer, {})] }) })] }), _jsx(HelpButton, {}), _jsx(AssetReportButton, {})] }));
};
export default App;
